atom/browser/api/atom_api_app.cc, atom/browser/api/atom_api_app.h, atom/browser/api/atom_api_web_contents.cc, atom/browser/api/atom_api_web_contents.h, atom/browser/api/atom_api_window.cc, atom/browser/api/atom_api_window.h, atom/browser/atom_browser_client.cc, atom/browser/atom_browser_client.h, atom/browser/lib/guest-view-manager.coffee, atom/browser/lib/guest-window-manager.coffee, atom/browser/native_window_mac.mm, atom/browser/web_view_guest_delegate.cc, atom/browser/web_view_guest_delegate.h, atom/renderer/lib/override.coffee, atom/renderer/lib/web-view/guest-view-internal.coffee, atom/renderer/lib/web-view/web-view-attributes.coffee, atom/renderer/lib/web-view/web-view-constants.coffee, atom/renderer/lib/web-view/web-view.coffee, docs/api/web-view-tag.md
There are still some electron tests that are failing, but they don't affect us so I will come back to them later. This requires a few small changes in browser-laptop before it should be merged
=> use native window opener functionality

atom/browser/api/atom_api_web_contents.cc, atom/browser/web_view_guest_delegate.cc, atom/renderer/api/atom_api_web_frame.cc, atom/renderer/atom_renderer_client.cc, atom/renderer/atom_renderer_client.h
also fixes a few other minor issues like links not re-using named frames
=> fix ctrl+click on windows

atom/browser/api/atom_api_web_contents.cc, atom/renderer/api/atom_api_web_frame.cc
fixes https://github.com/brave/browser-laptop/issues/460
fixes https://github.com/brave/browser-laptop/issues/469
=> correctly handle suppressed openers

atom/browser/api/atom_api_web_contents.cc, atom/browser/api/atom_api_web_contents.h, atom/browser/lib/guest-view-manager.js, atom/browser/web_view_guest_delegate.cc, atom/browser/web_view_guest_delegate.h, atom/renderer/api/atom_api_web_frame.cc, atom/renderer/api/atom_api_web_frame.h, atom/renderer/lib/web-view/web-view.js
=> add access to webview.contentWindow

atom/browser/api/atom_api_web_contents.cc, atom/browser/api/atom_api_window.cc, atom/browser/lib/guest-view-manager.js, atom/browser/web_contents_preferences.cc, atom/common/options_switches.cc, atom/common/options_switches.h, atom/renderer/atom_render_view_observer.cc, atom/renderer/atom_renderer_client.cc, atom/renderer/atom_renderer_client.h, atom/renderer/lib/web-view/web-view-attributes.js, atom/renderer/lib/web-view/web-view-constants.js, atom/renderer/lib/web-view/web-view.js, filenames.gypi
adds ipc support to contentScripts when running without node enabled
=> don't run node unless node is enabled or there is a preload script

atom/app/atom_main_delegate.cc, atom/browser/atom_browser_client.cc, atom/browser/web_contents_preferences.cc, atom/browser/web_contents_preferences.h, atom/common/javascript_bindings.cc, atom/common/javascript_bindings.h, atom/renderer/atom_render_view_observer.cc, atom/renderer/atom_renderer_client.cc, atom/renderer/atom_renderer_client.h, filenames.gypi
=> enable sandbox for renderers that don't run node

atom/browser/native_window_mac.mm
=> revert to upstream changes for window dragging

atom/browser/api/atom_api_extension.cc, atom/browser/api/atom_api_extension.h, atom/browser/api/atom_api_web_contents.cc, atom/browser/api/atom_api_web_contents.h, atom/browser/atom_browser_context.cc, atom/browser/atom_browser_context.h, atom/browser/extensions/atom_extensions_browser_client.cc, atom/browser/web_contents_preferences.h, atom/common/api/resources/ipc_bindings.js, lib/browser/api/navigation-controller.js, lib/browser/guest-view-manager.js, lib/renderer/override.js, lib/renderer/web-view/guest-view-internal.js
@bbondy 
fixes https://github.com/brave/browser-laptop/issues/1633
=> let the navigation controller manage history

atom/browser/api/atom_api_web_contents.cc, atom/browser/api/atom_api_web_request.cc, atom/browser/api/atom_api_web_request.h
=> add webRequest fetch method for non-webcontents url requests

atom/common/native_mate_converters/net_converter.cc, docs/api/app.md, docs/api/web-contents.md
Also update `fingerprint` getting method. The original one will be [removed](https://codereview.chromium.org/2000503002) in the future.
=> Refiling PR for #25

atom/common/native_mate_converters/net_converter.cc
Suggestion from [upstream](https://github.com/electron/electron/pull/6529)
=> Using base::HexEncode()

atom/browser/native_window_mac.mm, atom/common/platform_util.h, atom/common/platform_util_mac.mm
fix https://github.com/brave/browser-laptop/issues/2400
=> Swipe back/forward should respect system preferences

atom/browser/api/atom_api_system_preferences.cc, atom/browser/api/atom_api_system_preferences.h, atom/browser/api/atom_api_system_preferences_mac.mm, atom/browser/native_window_mac.mm, atom/common/platform_util.h, atom/common/platform_util_mac.mm, docs/api/system-preferences.md
Suggestion from upstream
https://github.com/electron/electron/pull/6686
=> Add IsSwipeTrackingFromScrollEventsEnabled in system prefs

atom/browser/native_window_mac.h, atom/browser/native_window_mac.mm
Fix https://github.com/brave/browser-laptop/issues/2548
=> Fix scroll conflict

package.json
=> Add npm task for libchromiumcontent build and bootstrap

atom/browser/autofill/atom_autofill_client.cc
Changes needed to fix https://github.com/brave/browser-laptop/issues/3359
=> Changes needed to fix autofill context menu position

atom/browser/autofill/atom_autofill_client.cc, atom/browser/autofill/atom_autofill_client.h
fix https://github.com/brave/browser-laptop/issues/3398
auditor: @bridiver
=> Create stub IdentityProvider

atom/renderer/content_settings_client.cc, atom/renderer/content_settings_client.h, lib/browser/guest-view-manager.js, lib/renderer/web-view/guest-view-internal.js
required by https://github.com/brave/browser-laptop/issues/3443
auditors: @bridiver
=> Emit block insecure content events

atom/browser/api/atom_api_web_contents.cc, atom/browser/api/atom_api_web_contents.h, atom/browser/autofill/atom_autofill_client.cc, atom/browser/autofill/atom_autofill_client.h, lib/browser/api/extensions.js
fixes some potential crashes and a few other minor changes
cc: @bbondy @darkdh
=> don't call autofill methods on potentially null values

atom/browser/api/atom_api_protocol.cc, atom/browser/api/atom_api_protocol.h
cc @bbondy @diracdeltas 
will require the following changes in browser-laptop
```
diff --git a/app/ledger.js b/app/ledger.js
index cb6f866..a7fdbb5 100644
--- a/app/ledger.js
+++ b/app/ledger.js
@@ -27,7 +27,6 @@ const util = require('util')
const electron = require('electron')
const app = electron.app
const ipc = electron.ipcMain
-const protocolHandler = electron.protocol
const session = electron.session
const acorn = require('acorn')
@@ -159,9 +158,10 @@ var boot = () => {
*/
if (ipc) {
-  ipc.on(messages.CHECK_BITCOIN_HANDLER, () => {
+  ipc.on(messages.CHECK_BITCOIN_HANDLER, (event, partition) => {
+    let protocolHandler = session.fromPartition(partition).protocol
if (typeof protocolHandler.isNavigatorProtocolHandled === 'function') {
-      ledgerInfo.hasBitcoinHandler = …
```
=> use the browser context provided by the session

package.json
Tested and works great! (previous updates to npm task were not fully tested because of problems w/ browser-laptop on Windows)
Auditors: @bridiver
=> Tweak to Windows npm task for build/install.

atom/browser/api/atom_api_autofill.cc, atom/browser/api/atom_api_autofill.h
Required by https://github.com/brave/browser-laptop/issues/3458
=> Add clearAutocompleteData & clearAutofillData

brave/browser/brave_browser_context.cc
auditors: @diracdeltas, @darkdh 
related: https://github.com/brave/browser-laptop/pull/3808
=> add overlay prefs for private profiles

chromium_src/chrome/browser/importer/importer_list.cc
fix https://github.com/brave/browser-laptop/issues/4275
Auditor: @bbondy
=> Do not claim the capability without support importing cookies from IE

atom/browser/importer/profile_writer.cc
=> Emit png_data for invalid favicon_url of import from HTML

chromium_src/chrome/common/importer/edge_importer_utils_win.cc
fix https://github.com/brave/browser-laptop/issues/4679
=> Fix egde legacy mode detection

atom/browser/browser_linux.cc, atom/browser/browser_win.cc, docs/api/app.md
1. Set default protocol for win8 and win10
2. Get/Set default protocol for linux
=> Extend default protocol client

atom/utility/importer/chrome_importer.cc, atom/utility/importer/chrome_importer.h
=> Add favicon for chrome bookmarks import

atom/browser/browser_win.cc
fix https://github.com/brave/browser-laptop/issues/5000
Auditors: @bbondy
=> Check only UrlAssociations on win8+

atom/browser/browser_win.cc
and Set Default Browser
fix https://github.com/brave/browser-laptop/issues/5028
Auditors: @bbondy, @bridiver
=> Temporary solution for solving conflict between RegisterProtocolHandler

atom/common/api/resources/ipc_bindings.js
fix https://github.com/brave/browser-laptop/issues/4686
@Auditors: @bridiver, @jonathansampson
=> Overrides window.open for background and extension page

atom/common/api/resources/context_menus_bindings.js, lib/browser/api/extensions.js
=> Emit extension icon

atom/browser/web_contents_permission_helper.cc, atom/browser/web_contents_permission_helper.h
Fix https://github.com/brave/browser-laptop/issues/5378
Auditors: @bridiver
=> Use security origin for media access permission requests

atom/common/importer/chrome_importer_utils.h, atom/common/importer/chrome_importer_utils_linux.cc, atom/common/importer/chrome_importer_utils_mac.mm, atom/common/importer/chrome_importer_utils_win.cc, chromium_src/chrome/browser/importer/importer_list.cc
fix https://github.com/brave/browser-laptop/issues/5463
Autidors: @bbondy, @bsclifton
=> Add chromium & chrome canary to importer list

BUILD.gn, app/linux/BUILD.gn, atom/app/atom_main.cc, atom/app/atom_main_delegate.cc, atom/browser/BUILD.gn, atom/browser/api/atom_api_global_shortcut.cc, atom/browser/native_window.h, atom/browser/native_window_views.cc, atom/browser/native_window_views.h, brave/browser/brave_content_browser_client.cc, brave/common/brave_paths.cc, build/BUILD.gn, build/node/BUILD.gn, chromium_src/BUILD.gn, vendor/brightray/BUILD.gn, vendor/brightray/browser/inspectable_web_contents.h, vendor/brightray/browser/inspectable_web_contents_impl.cc, vendor/brightray/browser/inspectable_web_contents_impl.h, vendor/brightray/browser/inspectable_web_contents_view.h
Basic building works.
https://github.com/brave/electron/issues/94 for outstanding
issues.
=> Repair linux build

BUILD.gn, atom/browser/api/atom_api_global_shortcut.cc, brave/browser/brave_content_browser_client.cc, brave/common/brave_paths.cc, vendor/brightray/BUILD.gn
Repair gpu services
A bit of path cleanup
Tie some stuff to linux.
Nits
=> Repair linux build p2

app/linux/BUILD.gn, atom/common/native_mate_converters/callback.h, tools/js2asar.py, vendor/brightray/browser/browser_main_parts.cc
Actually activate j2asar
OverrideLinuxAppDataPath now returns boolean
Modify js2asar to support linux
=> Linux Fix part3

atom/browser/api/atom_api_web_contents.cc, atom/browser/atom_browser_client.cc, brave/renderer/brave_content_renderer_client.cc, chromium_src/chrome/renderer/content_settings_observer.cc
Auditors: @bridiver, @bbondy, @darkdh
=> Windows build fixes

app/linux/BUILD.gn
This will strip and create symbols on linux
=> Create_dist should strip on linux 

README.md
Lots of changes; most importantly:
- Describe project
- Update links to documentation
- Add links for community
- Remove information which is no longer relevant
- travis.ci status for electron
- electron banner
- translated electron docs
- etc
=> Update README, links, etc.

package.json
Remove obsolete npm tasks
Auditors: @bbondy, @bridiver, @darkdh, @posix4e
=> Remove obsolete npm tasks

BUILD.gn, app/win/BUILD.gn
=> Add widevinecdmadapter.dll to dist on Windows

atom/browser/net/atom_network_delegate.cc
=> Get correct tab ID for websocket requests

app/win/BUILD.gn, atom/browser/BUILD.gn, atom/browser/native_window_views.cc, atom/browser/native_window_views.h, atom/browser/native_window_views_win.cc, brave/browser/extensions/path_bindings.cc, brave/common/extensions/asar_source_map.cc
Includes fixes I needed to get compiling on Windows (may or may not be merged already; fixes + lint fix)
I sent a copy of the binary to @jonathansampson via Slack; please try it out and let me know how it looks (with and without the option enabled)
=> Fix windows resize a11y

patches/master_patch.patch
@Auditors: @bridiver, @bbondy, @jonathansampson
=> Check autoplay setting on shouldAutoplay and isGestureNeededForPlayback

patches/master_patch.patch
Reverts brave/muon#185
need to update for cr58 
cc @darkdh
=> Revert "Check autoplay setting on shouldAutoplay and isGestureNeededForPlayback"

atom/browser/api/atom_api_importer.cc, brave/browser/BUILD.gn, brave/browser/importer/brave_external_process_importer_host.cc, brave/browser/importer/brave_external_process_importer_host.h, brave/utility/importer/chrome_importer.cc, brave/utility/importer/firefox_importer.cc, brave/utility/importer/importer_creator.cc, patches/master_patch.patch
fix https://github.com/brave/browser-laptop/issues/8849
=> Fix broken import cookies

atom/browser/ui/views/menu_bar.cc, chromium_src/BUILD.gn, vendor/brightray/browser/browser_main_parts.cc, vendor/brightray/browser/browser_main_parts.h
=> WIP: Fix LayoutProvider not being available on Debian

atom/browser/api/atom_api_autofill.cc
required by https://github.com/brave/browser-laptop/pull/9085
=> Fix missing add observer for password store observer

atom/browser/api/atom_api_web_contents.cc, atom/browser/extensions/tab_helper.cc, atom/browser/extensions/tab_helper.h, chromium_src/chrome/browser/extensions/extension_tab_util.cc
Required to fix https://github.com/brave/browser-laptop/issues/9395
=> Set the tab opener

chromium_src/BUILD.gn
Auditors: @bridiver, @diracdeltas, @bsclifton
=> Pull deps of gnome keyring and libsecret

atom/browser/api/atom_api_web_contents.cc
=> add option for replacing current entry in navigation

atom/browser/api/atom_api_cookies.cc, lib/browser/api/extensions.js
brave/browser-laptop#9769
auditors:
@jonathansampson
=> chrome.cookies.get returns one cookie not array

atom/browser/api/atom_api_dialog.cc, atom/browser/atom_download_manager_delegate.cc, atom/browser/common_web_contents_delegate.cc, atom/browser/ui/file_dialog.h, atom/browser/ui/file_dialog_gtk.cc, atom/browser/ui/file_dialog_mac.mm, atom/browser/ui/file_dialog_win.cc, atom/browser/web_dialog_helper.cc, lib/browser/api/dialog.js
mainly cherry-pick the commit of https://github.com/electron/electron/commit/a33ffd621f184916e76fce43100701264321e2c2#diff-1723fc06542f55eca6f1abc2a3988822
fix https://github.com/brave/browser-laptop/issues/698
=> Use callback dialog methods in RunFileChooser

lib/browser/init.js
=> Add tray icon workaround for Pantheon.

brave/utility/importer/chrome_importer.cc
=> Fix compile error after rebase to 60

BUILD.gn, brave/utility/importer/chrome_importer.cc, patches/master_patch.patch
fixes https://github.com/brave/browser-laptop/issues/10045
=> Import encrypted cookies from Chrome/Chromium

brave/common/extensions/url_bindings.cc
Fixes https://github.com/brave/browser-laptop/issues/10342
I updated `FormatForDisplay` to allow for an override (if needed). However, the JavaScript binding is still only using the default implementation (hence the static cast). If we ever needed a version which kept space, we could create a new binding like `FormatEscapingSpaces` (which then calls `FormatForDisplay(args, net::UnescapeRule::SPACES)`
=> Fix URL formatting; spaces were not being escaped which caused several problems.

atom/browser/api/atom_api_web_contents.cc, brave/common/extensions/shared_memory_bindings.cc
=> fix linux crash on shutdown and race condition for close/unmap

app/mac/BUILD.gn, atom/app/atom_content_client.cc, patches/master_patch.patch
Auditors: @bridiver, @bsclifton, @bbondy
=> Create Widevine Resources.bundle without signature

app/mac/BUILD.gn, patches/master_patch.patch
=> Create Widevine Resources.bundle at browser-laptop.

README.md
=> replace brave's channel in electron slack with discord

atom/browser/importer/profile_writer.cc
fix https://github.com/brave/browser-laptop/issues/11089
Auditors: @bbondy, @bsclifton
=> Fix secure cookies using http url

atom/browser/api/atom_api_web_contents.cc, atom/browser/api/trackable_object.h, vendor/native_mate/native_mate/function_template.h
check wrapper before setting internal fields
fix #315
=> handle web_contents destruction more consistently for guests

chromium_src/BUILD.gn, vendor/brightray/browser/browser_context.cc, vendor/brightray/browser/url_request_context_getter.cc
possible fix for https://stats.brave.com/dashboard#crash/59ce679be24b49001d479db0
=> use thread safe proxy and cleanup shutdown

atom/browser/net/atom_network_delegate.cc, atom/browser/net/atom_network_delegate.h
=> use weak ptr for callbacks that may outlive the network delegate

vendor/brightray/browser/inspectable_web_contents_impl.cc, vendor/brightray/browser/inspectable_web_contents_impl.h
=> url fetch requests may outlive the webcontents they are associated with

brave/renderer/extensions/web_frame_bindings.cc
=> check for null/undefined values when iterating over path

BUILD.gn
=> Add chrome_elf.dll to create_dist input

atom/browser/api/atom_api_download_item.cc, atom/browser/api/atom_api_download_item.h, atom/browser/api/atom_api_session.cc, atom/browser/api/atom_api_session.h, atom/browser/api/atom_api_web_contents.cc, atom/browser/api/atom_api_web_contents.h, atom/browser/atom_browser_context.cc, atom/browser/atom_download_manager_delegate.cc, atom/browser/atom_download_manager_delegate.h, atom/common/platform_util_linux.cc, atom/common/platform_util_mac.mm, atom/common/platform_util_win.cc, brave/browser/brave_browser_context.cc, chromium_src/BUILD.gn
pre-req for https://github.com/brave/browser-laptop/issues/11326
=> fix download handling for cr62

atom/browser/atom_browser_main_parts.cc
probable fix for https://github.com/brave/browser-laptop/issues/11604
=> disable ukm

atom/browser/extensions/tab_helper.cc, atom/browser/extensions/tab_helper.h, atom/browser/net/atom_network_delegate.cc, atom/browser/net/atom_network_delegate.h, brave/browser/guest_view/tab_view/tab_view_guest.cc
Fix https://github.com/brave/browser-laptop/issues/11621
See also:
https://chromium.googlesource.com/chromium/src/+/1b8747c4fed55e7fde4344eb0a71463855096502%5E%21/
=> Fix filtering not knowing tabId

common.gypi
https://chromium.googlesource.com/chromium/src.git/+/a3cf4d27ce27706c9cb253216a98f0bafd20096e
=> compiler_version.py got removed in

atom/browser/extensions/atom_extension_system.cc
fix https://github.com/brave/browser-laptop/issues/11578
supersedes https://github.com/brave/muon/pull/348
=> store installed state in extension prefs

atom/browser/api/atom_api_web_contents.cc
fix https://github.com/brave/browser-laptop/issues/11637
=> PrintViewManagerBasic -> PrintViewManager

brave/browser/guest_view/tab_view/tab_view_guest.cc
Needed for https://github.com/brave/browser-laptop/pull/10831 to display
about:newtab page
=> Set parent_partition to '' for private session tabs

brave/renderer/brave_content_renderer_client.cc, brave/renderer/brave_content_renderer_client.h
fix https://github.com/brave/browser-laptop/issues/11716
=> disable safe_browsing throttles

chromium_src/chrome/browser/printing/print_preview_message_handler.cc, chromium_src/chrome/browser/printing/print_preview_message_handler.h
fix https://github.com/brave/browser-laptop/issues/11471
=> fix print to pdf on windows

atom/app/atom_main.cc
ensure crash dump dir is always correct
fix #368
=> integrate changes from #369

atom/browser/api/atom_api_web_contents.cc, atom/common/javascript_bindings.cc, brave/common/extensions/shared_memory_bindings.cc
fix https://github.com/brave/browser-laptop/issues/12246
=> only send shared memory ipc messages to webui or extension context

brave/common/extensions/shared_memory_bindings.cc
fix https://github.com/brave/browser-laptop/issues/12317
=> Another read only memory handle CHECK guard failed

atom/browser/api/atom_api_app.cc, atom/browser/api/atom_api_app.h
needed for https://github.com/brave/internal/issues/176 which is supposed to go in 0.20.x
=> expose app API for boolean browser prefs

patches/master_patch.patch
=> Prompt autoplay permission even for muted video

brave/browser/password_manager/brave_password_manager_client.cc
fix https://github.com/brave/browser-laptop/issues/10566
=> Respect credentials_enable_service before filling credentials

lib/browser/api/extensions.js
fix https://github.com/brave/browser-laptop/issues/12883
=> always check `isDestroyed` in `setImmediate`

chromium_src/BUILD.gn, chromium_src/chrome/browser/browser_process_impl.cc
prereq for https://github.com/brave/browser-laptop/pull/12888
=> add chrome gpu mode manager

atom/browser/native_window_views.cc
=> make all hidden windows non-focusable

atom/browser/browser_win.cc
fix https://github.com/brave/browser-laptop/issues/12797
Auditors: @bridiver, @diracdeltas
=> Appending `--` when writing open command

brave/browser/brave_javascript_dialog_manager.cc
=> Use callback wrapper to prevent double std::move()

atom/browser/atom_browser_main_parts.cc
=> initialize fields trials earlier

atom/browser/atom_browser_main_parts.cc
fix https://github.com/brave/browser-laptop/issues/13090
=> ensure that `session-created` fires for the main browser context

atom/browser/native_window_views.cc
fix #467
Auditor: @bridiver, @bbondy
=> Don't set ACTIVATABLE_NO when `show: false` on Linux

DEPS
Fix https://github.com/brave/browser-laptop/issues/13092
Fix https://github.com/brave/browser-laptop/issues/13038
This commit updates ad-block to the latest version with a fix for better Swedish ad filtering!
cc @bbondy
=> Update ad-block dependency to latest version

atom/browser/common_web_contents_delegate.cc
fix https://github.com/brave/browser-laptop/issues/13254
=> Fix empty devtool profile

atom/browser/atom_download_manager_delegate.cc, atom/browser/atom_download_manager_delegate.h, brave/browser/guest_view/tab_view/tab_view_guest.cc
=> PR 503 followup

lib/muon/module_system/commonjs.js
https://chromium.googlesource.com/chromium/src.git/+/312031eec9c97d5cb9dea801f4f3cefe2f3ad937%5E%21/
fix https://github.com/brave/browser-laptop/issues/13366
=> Remove AMD define for

atom/browser/atom_download_manager_delegate.cc
Use last active native window if there is no window related with download item.
=> Handle download from newly created tab

atom/browser/atom_download_manager_delegate.cc
Avoid always closing tab whether it is newtab on download or not.
=> Fix https://github.com/brave/browser-laptop/issues/13365

atom/browser/atom_browser_main_parts.cc
https://chromium.googlesource.com/chromium/src.git/+/4c4f02491a27890c14347f352150c260d815c963
fix https://github.com/brave/browser-laptop/issues/13433
=> Turn off wheel scroll latching

atom/utility/atom_content_utility_client.cc, brave/browser/brave_content_browser_client.cc
https://chromium.googlesource.com/chromium/src/+/232407a96854b0c886ccd5e7a6f65c1efc9c9818
https://chromium.googlesource.com/chromium/src/+/407c3fcf555e8df54e8236531847720a0c3cbbed
fix https://github.com/brave/browser-laptop/issues/13546
Auditors: @bsclifton, @bridiver 
Verified by @bsclifton
=> Fix printing service on Windows

patches/master_patch.patch
fix https://github.com/brave/browser-laptop/issues/13580
=> Handle mouse up/down in async

atom/browser/atom_resource_dispatcher_host_delegate.cc, atom/browser/web_contents_permission_helper.cc, atom/browser/web_contents_permission_helper.h, brave/browser/brave_permission_manager.cc
Testing Instructions here: https://github.com/brave/browser-laptop/pull/13475
Fixes: https://github.com/brave/browser-laptop/issues/13471
=> Incorrect hosts were granted `OpenExternal` permissions

brave/browser/BUILD.gn, brave/browser/brave_browser_context.cc, brave/browser/brave_browser_context.h, brave/browser/net/proxy/proxy_config_service_tor.cc, brave/browser/net/proxy/proxy_config_service_tor.h, brave/utility/tor/tor_impl.cc
https://github.com/brave/muon/pull/473#discussion_r177619044
=> Replace GURL for tor browser context

chromium_src/BUILD.gn, patches/master_patch.patch
//net and //electron/chromium_src/net are mutually depended
Auditors: @bridiver, @riastradh-brave
=> Fix undefined symbols of chromium_src/net on Windows

brave/browser/brave_browser_context.cc
introduced by 25c0a4f2fc1e524eff41bf9132354c23e37270b9
=> Fix windows build error of incomplete `PasswordWebDataService`

brave/browser/brave_browser_context.cc
Fixes: https://github.com/brave/muon/issues/602
=> Add Overlay pref store for tor partition

brave/utility/importer/chrome_importer.cc
=> chromium 66.0.3359.181 linux build fix

chromium_src/BUILD.gn, chromium_src/chrome/browser/themes/theme_service.cc
=> build fix for c67 merge

DEPS
=> Update ad-block to 4.0.1 and its dependency

DEPS
=> Use brave repo for brave-core parity

DEPS
https://github.com/brave/ad-block/pull/112
https://github.com/brave/tracking-protection/pull/19
=> ad-block and tracking-protection build fix

atom/browser/net/asar/url_request_asar_job.cc, atom/browser/net/url_request_buffer_job.cc, atom/browser/net/url_request_string_job.cc, atom/common/atom_constants.cc, atom/common/atom_constants.h
fix https://github.com/brave/browser-laptop/issues/14967
Auditors: @bridiver, @diracdeltas, @bbondy
=> Do not add "Access-Control-Allow-Origin: *" to response header
