atom/app/atom_main_delegate.cc
atom/app/atom_main_delegate.h

fixes https://github.com/brave/browser-laptop/issues/743

run content scripts on linux

---

atom/common/native_mate_converters/net_converter.cc
docs/api/app.md
docs/api/web-contents.md

This is for brave/browser-laptop#2428
CC @bbondy @diracdeltas

Add more detail attributes for certificate-error

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
package.json

cc: @bridiver 
Getting familiar with electron :smile: Adding a method to help w/ getting information used in history.
Would be great if you can help me understand how to test locally (I tried a few things, no luck- I'm ready to update docs after I figure it out)

Adding NavigationEntry wrapper method for getting history page title.

---

atom/browser/api/atom_api_session.cc
atom/browser/api/atom_api_session.h

This is needed for https://github.com/brave/browser-laptop/issues/2890.
Maybe it should just be on by default instead of as a session method, not sure.
Auditors: @bbondy

Add session method to enable Brotli compression

---

docs/development/build-instructions-windows.md
package.json

Created while troubleshooting https://github.com/brave/browser-laptop/issues/3142
- Added npm task for installing local electron into browser-laptop
- Updated two lines in docs to reference npm  tasks

Added npm task for copying on Windows; updated docs

---

atom/renderer/content_settings_client.cc
atom/renderer/content_settings_client.h

Fix https://github.com/brave/browser-laptop/issues/3214
auditors: @bridiver

Block filesystem access when cookies are blocked

---

atom/browser/api/atom_api_autofill.cc
atom/browser/api/atom_api_autofill.h
atom/browser/api/atom_api_session.cc
atom/browser/api/atom_api_session.h
atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/browser/autofill/atom_autofill_client.cc
atom/browser/autofill/atom_autofill_client.h
atom/browser/autofill/personal_data_manager_factory.cc
atom/browser/autofill/personal_data_manager_factory.h
autofill.gypi
brave/browser/brave_browser_context.cc
brave/browser/brave_browser_context.h
brave/renderer/brave_content_renderer_client.cc
docs/api/autofill.md
electron.gyp
extensions.gypi
lib/browser/api/extensions.js
lib/browser/guest-view-manager.js
lib/renderer/web-view/guest-view-internal.js

fix https://github.com/brave/browser-laptop/issues/860
auditor: @bridiver, @bbondy

Add Autofill support

---

autofill.gypi

used by CryptProtectData / CryptUnprotectData.
Auditors: @darkdh
Tested on Windows 10 and it works great :smile:

Fix linking issue on Windows; add reference to crypt32.lib

---

package.json

Something I had forgotten to push after originally adding the task w/ https://github.com/brave/electron/commit/035bdf9dd9654a9e17c5e70783a4caef9f38c4fc

Fix typo in Windows specific npm task

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
docs/api/web-contents.md
docs/api/web-view-tag.md
lib/renderer/web-view/web-view.js

To help detect frame initial state change.
Prereq for fixing https://github.com/brave/browser-laptop/issues/3162
For an example using this, see https://github.com/brave/browser-laptop/compare/master...ayumi:add-is-initial-blank-navigation?expand=1

Expose NavigationController::IsInitialBlankNavigation

---

atom/browser/api/atom_api_window.cc
atom/browser/api/atom_api_window.h
atom/browser/native_window.cc
atom/browser/native_window.h
atom/browser/native_window_mac.h
atom/browser/native_window_mac.mm
atom/browser/native_window_observer.h
docs/api/browser-window.md

Emit scroll-touch-edge event instead of changing the behavior of scrollll-touch-begin/end

---

atom/browser/api/atom_api_autofill.cc

Replace SaveImportedProfile and SaveImportedCreditCard by Add/UpdateProfile and Add/UpdateCreditCard

---

atom/renderer/atom_render_view_observer.cc

Fixes mouse coordinates for Windows when display is set to a higher DPI (ex: enlarged by 150% using display settings)
Fixes upstream electron issue https://github.com/electron/electron/issues/7347
Auditors: @bridiver @bbondy

Fixes mouse coordinates for Windows when display is set to a higher DPI

---

atom/browser/native_window_views.cc

Properly handle the bounds on frameless window type (win32 only)
Auditors: @bridiver @bbondy @jonathansampson

Possible fix for issues seen on frameless window (Windows) when at 200%

---

atom/browser/api/atom_api_autofill.cc
atom/browser/api/atom_api_autofill.h

Make Autofill as a PersonalDataManagerObserver

---

atom/browser/browser_win.cc

fix https://github.com/brave/browser-laptop/issues/4937

Add reading/writing UrlAssociations for default protocol get/set

---

atom/browser/api/atom_api_web_contents.cc
lib/renderer/web-view/guest-view-internal.js

This is needed to mitigate https://github.com/brave/browser-laptop/issues/4973,
we should only set the frame title on navigation if it was not renderer-initiated
(ex: by clicking the back/forward buttons)
Auditors: @bbondy

add isRendererInitiated property on did-navigate event

---

atom/common/api/resources/context_menus_bindings.js
lib/browser/api/extensions.js

Auditors: @bridiver, @jonathansampson

Add chrome.contextMenus.create and chrome.contextMenus.removeAll

---

atom/common/api/resources/context_menus_bindings.js

Return menuId and throws error for non support properties

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
lib/browser/guest-view-manager.js
lib/renderer/web-view/guest-view-internal.js

Needed to address
https://github.com/brave/browser-laptop/issues/5490 and
https://github.com/brave/browser-laptop/issues/5238
Auditors: @bsclifton @bbondy

Add webview event for security state changes

---

atom/browser/api/atom_api_web_contents.cc
lib/browser/guest-view-manager.js
lib/renderer/web-view/guest-view-internal.js

Needed for https://github.com/brave/browser-laptop/issues/5524
Auditors: @bridiver @darkdh

Emit more specific security state change events

---

patches/master_patch.patch
patches/v8/filter.patch

patches from now on will use full-index to eliminate prefix difference among git versions

Add patch to fix ERR_CERTIFICATE_TRANSPARENCY_REQUIRED timebomb

---

app/win/BUILD.gn

fix https://github.com/brave/browser-laptop/issues/5926

Declare DPI Awareness

---

atom/app/atom_main_delegate.cc

(unintentionally broke with https://github.com/brave/electron/commit/7a183f20aad1e4668c3b981454c0a35edf577cb3#diff-854fac274f5ec2e739cc9ca5cea0d445)
Fixes https://github.com/brave/browser-laptop/issues/5938
Auditors: @bridiver, @darkdh

Fix relaunching on Windows / Linux 

---

atom/browser/native_window_views.cc
atom/browser/ui/win/atom_desktop_window_tree_host_win.cc
atom/browser/ui/win/atom_desktop_window_tree_host_win.h

Provide handler to remove border for frameless windows (Win32 only)
Fixes https://github.com/brave/browser-laptop/issues/6258
Auditors: @bbondy, @bridiver

Provide handler to remove border for frameless windows (Win32 only)

---

package.json

for #132
now that `./script/build.py` no longer exists, the associated `package.json` scripts should be removed:
- `npm run build`
- `npm run browser-build`
- etc
cc @bsclifton

remove script/build.py references from package.json

---

app/win/BUILD.gn

fix https://github.com/brave/browser-laptop/issues/6522
Auditors: @bbondy, @bridiver, @bsclifton (summon three Brian in a row)

Fix exception of couldn't delay loading ole32.dll

---

atom/browser/native_window_views_win.cc
atom/browser/ui/win/atom_desktop_window_tree_host_win.cc
atom/browser/ui/win/atom_desktop_window_tree_host_win.h

Was noticed when upstreaming border fixes to electron with https://github.com/electron/electron/pull/8404
After @kevinsawicki saw same issue, I fixed with https://github.com/electron/electron/pull/8404/commits/9e0547b98f8b7f3a572aa1cf9770f434c8fdeed9 (same as this fix)
Tested on Windows 10 anniversary edition at 200% DPI and confirmed issue is fixed with this
Fixes https://github.com/brave/browser-laptop/issues/4216
Auditors: @bbondy, @darkdh, @bridiver

Fix for rounded border issue on 200% DPI (Windows).

---

patches/master_patch.patch

https://chromium.googlesource.com/chromium/src.git/+/3a38c33c398189620281ad19a0f8e5b7f6ac3e69
must pick these commits in order first and do some proper modification
1. https://chromium.googlesource.com/chromium/src/+/605fa62ea2c9ac2924ff08f21106775d412bed5b
2. https://chromium.googlesource.com/chromium/src/+/3fd7c79eea0cb0f981a73b1264568366214f229e
3. https://chromium.googlesource.com/chromium/src/+/78115b26dfafd0fca676ac33caabd3aa8b43ecf4
4. https://chromium.googlesource.com/chromium/src/+/69969af74bfff920f5fdcc2aa547ea4af2d477d2
should be removed when upgrading to chromium 55
fix https://github.com/brave/browser-laptop/issues/6656
Auditors: @bbondy, @bridiver, @bsclifton

Cherry-pick "Save a copy when advancing to dependent GIF and WebP animation frames"

---

BUILD.gn

The absence of both .pak files in the final package (prebuilt) was causing the borders of the select box to be bright yellow (#FFFF00)
These were removed with https://github.com/brave/muon/commit/29ab58342ec11a37d55f2f2ad7e32c89238b7976 (not sure if this was intentional)
Fixes https://github.com/brave/browser-laptop/issues/7184
Auditors: @darkdh, @bbondy

Fix yellow border issue when rendering select control on Windows

---

BUILD.gn

These were unintentionally removed with https://github.com/brave/muon/commit/29ab58342ec11a37d55f2f2ad7e32c89238b7976 and were added back on Windows with https://github.com/brave/muon/commit/662bc7a444006eca8bb8e43eeb07f6c8d5d66f45
Fixes https://github.com/brave/browser-laptop/issues/7260

Re-add missing pak files (linux). 

---

atom/app/atom_main_delegate.cc
atom/browser/api/atom_api_web_contents.cc
atom/utility/atom_content_utility_client.cc

dcbdf36 is for printing dialog is not shown introduced by 39054e8
8ed07a8 fixes https://github.com/brave/browser-laptop/issues/7326

Printing fix

---

chromium_src/chrome/browser/printing/print_preview_message_handler.cc
lib/browser/api/web-contents.js

fix https://github.com/brave/browser-laptop/issues/7416
1. Use RenderFrameHost instead of RenderViewHost
(https://chromium.googlesource.com/chromium/src.git/+/cb959ce66a9a89b6f100795bb33292439a7ed7de)
2. Add scaleFactor for check in https://chromium.googlesource.com/chromium/src.git/+/56.0.2924.87/printing/print_settings_conversion.cc#187
(https://chromium.googlesource.com/chromium/src.git/+/769ffdf779d83399a6f219e2637c6469ab94da0e
3. Add correct HostID & RountingID for CreatePrinterQuery
(https://chromium.googlesource.com/chromium/src.git/+/56.0.2924.87/chrome/browser/printing/printing_message_filter.cc#267)

Fix printToPDF on chromium56

---

atom/browser/autofill/atom_autofill_client.cc

There will be a follow-up cleanup in browser-laptop and I will mark
issue fixed there.
Address https://github.com/brave/muon/commit/fcaecc2f6230e700b858153c768fbe725027d1d7

Hide autofill popup only when webcontent is focused

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
atom/browser/common_web_contents_delegate.cc
atom/browser/common_web_contents_delegate.h
atom/common/api/resources/web_view_api_bindings.js
brave/browser/BUILD.gn
brave/browser/certificate_viewer_mac.mm
chromium_src/BUILD.gn
lib/browser/api/browser-window.js

Currently only support on mac and windows
fix brave/browser-laptop#2611

View certificate support

---

brave/common/extensions/asar_source_map.cc
patches/master_patch.patch

Fix https://github.com/brave/browser-laptop/issues/7210
Address https://github.com/brave/browser-laptop/issues/6902#issuecomment-285927831

Make Linux sandbox error message more useful

---

atom/browser/javascript_environment.cc

The directory was not being set correctly for packaged builds.  In particular base::DIR_SOURCE_ROOT was returning a directory that wasn't correct.   In dev builds it would return /Users/bbondy/projects/brave/browser-laptop-bootstrap/src/browser-laptop and in packaged builds that were run from /Users/bbondy/projects/brave/browser-laptop-bootstrap/src/browser-laptop/Brave-darwin-x64/Brave.app it would return /Users/bbondy/projects/brave/browser-laptop-bootstrap/src/.
To fix this I just use the resource path's app.asar file if it exists first and only fallback to the search path if that doesn't exist since it only exists in packaged builds.
Fix https://github.com/brave/browser-laptop/issues/8195
Auditors: @bridiver

Use the correct JavaScript environment search path dir

---

atom/common/api/resources/windows_bindings.js
lib/browser/api/extensions.js

Event API: https://developer.chrome.com/extensions/windows#event-onFocusChanged

add extension chrome.windows.onFocusChanged

---

chromium_src/chrome/browser/browser_process_impl.cc

This get turned on by default in
https://chromium.googlesource.com/chromium/src/+/9e1897b5c7dab9c190fc3c919a1c4662af63b3e6
fix https://github.com/brave/browser-laptop/issues/8422

Disble Isolate Extensions by default

---

atom/browser/native_window_views.cc

Initial PR was done with https://github.com/brave/muon/pull/191 but I missed https://github.com/electron/electron/commit/dcf6c52f51bcf3635bd97238a851f73cda1d7b40
Fixes https://github.com/brave/browser-laptop/issues/8839
Auditors: @bbondy, @bridiver

Menu is now properly hidden when toggled (only used in Brave for Linux).

---

brave/browser/password_manager/brave_password_manager_client.cc

fix https://github.com/brave/browser-laptop/issues/9028

Using pending credential instead of submitted form which might contain empty username

---

atom/renderer/api/atom_api_spell_check_client.h
brave/renderer/extensions/web_frame_bindings.cc

see chromium commits:
https://chromium.googlesource.com/chromium/src.git/+/62dc793dc640ae5fd16d571a0c9199fe0fb740d0
->
https://chromium.googlesource.com/chromium/src.git/+/81bfb1741ab51947f5fc7c741eadd92779fe13b2
->
https://chromium.googlesource.com/chromium/src.git/+/1c4d759e44259650dfb2c426a7f997d2d0bc73dc
->
https://chromium.googlesource.com/chromium/src.git/+/0c92b1cfa21b855c0e8c19f5550ae5209a325936
fix https://github.com/brave/browser-laptop/issues/9102

Call WebView:SetTextCheckClient in initialization

---

DEPS
atom/browser/api/atom_api_menu.cc
atom/browser/api/atom_api_menu.h
atom/browser/api/atom_api_menu_mac.h
atom/browser/api/atom_api_menu_mac.mm
atom/browser/api/atom_api_menu_views.cc
atom/browser/api/atom_api_menu_views.h
atom/browser/api/atom_api_window.h
atom/browser/api/trackable_object.h
atom/browser/ui/cocoa/atom_menu_controller.h
atom/browser/ui/cocoa/atom_menu_controller.mm
brave/common/extensions/url_bindings.cc
docs/api/menu.md
docs/tutorial/planned-breaking-changes.md
lib/browser/api/menu.js
spec/api-menu-spec.js

Manual application of electron patch https://github.com/electron/electron/pull/8702
Additional updates (per https://github.com/electron/electron/pull/8702)
Fixes https://github.com/brave/browser-laptop/issues/5470
- Default `async` to true for popup menus
- fix lint errors
- 1st commit: menus do not destroy themselves
- 2nd commit: menus destroy themselves

Mac async popup

---

lib/browser/api/extensions.js
lib/common/deep-equal.js

Fix https://github.com/brave/browser-laptop/issues/9313

Tab update events should only fire when data has changed

---

atom/browser/api/atom_api_cookies.cc
atom/browser/api/atom_api_cookies.h
atom/common/api/resources/cookies_bindings.js
lib/browser/api/extensions.js

See https://github.com/brave/vault-updater/pull/42

Add chrome.cookies.{getAll, set, get} for Pinterest Save Button extension, brave/browser-laptop#6366

---

brave/common/extensions/url_bindings.cc

Fix https://github.com/brave/browser-laptop/issues/9503
the only other difference that i can tell is that muon.url.parse does not have the `slashes` field. however its only use in browser-laptop can be replaced by the `origin` field.

Make muon.url.parse work more like Node's

---

atom/browser/ui/views/menu_bar.cc
atom/browser/ui/views/menu_bar.h

Keep reference to MenuDelegate as a member (so it won't go out of scope and auto-close/destroy).
Fixes https://github.com/brave/browser-laptop/issues/9470
Auditor: @darkdh

Fix broken menus on Linux / Gnome (introduced w/ C59)

---

atom/browser/api/atom_api_session.cc
atom/browser/api/atom_api_session.h

Make task_tracker an instance var on atom_api_session

---

atom/browser/importer/profile_writer.cc
brave/utility/importer/firefox_importer.cc
brave/utility/importer/firefox_importer.h
patches/master_patch.patch

Auditors: @darkdh
required by https://github.com/brave/browser-laptop/pull/9433

Enable importing passwords from Firefox

---

BUILD.gn
atom/common/importer/chrome_importer_utils.cc
brave/utility/brave_profile_import_handler.cc
brave/utility/importer/chrome_importer.cc
brave/utility/importer/chrome_importer.h
patches/master_patch.patch

fixes https://github.com/brave/browser-laptop/issues/9434
Auditors: @bridiver, @bbondy, @diracdeltas, @bsclifton
Mac:
master password will store in Chrome/Chromium Safe Storage
so we will ask users to access it
Windows:
Using `CryptProtectData` and `CryptUnprotectData`
`Usually, the only user who can decrypt the data is a user with the same logon
credentials as the user who encrypted the data`
Linux:
Using NativeBackEnd.
gnome-keyring which will be removed soon is deprecated by libsecret
KDE has a bug traking it #238

Import password from Chrome/Canary/Chromium

---

atom/app/atom_main_delegate.cc

read from Chrome native messaging host file

---

vendor/brightray/BUILD.gn
vendor/brightray/browser/url_request_context_getter.cc

CryptoDelegate being set incorrectly led to data in the cookie database being un-encrypted. 
fixes https://github.com/brave/browser-laptop/issues/10044
Note: Testing is still in progress

Encrypt cookies at rest (#10044)

---

brave/utility/importer/chrome_importer.cc

fixes https://github.com/brave/browser-laptop/issues/10043
Auditors: @bridiver, @diracdeltas, @bbondy

Fix SetCookieWithDetailsAsync with failure callback

---

chromium_src/chrome/renderer/extensions/chrome_extensions_dispatcher_delegate.cc

fix #269 
@bbondy I set this for 4.3 because it's meant to be a perf fix, but I can move to 4.4 if you want

add muon.shared_memory to protected renderer processes

---

lib/browser/api/browser-actions.js

Fixes https://github.com/brave/browser-laptop/issues/10224
To be merged into Muon 4.3.x (for use with browser-laptop 0.18.x hotfix)
Auditors: @jonathansampson

Fall back to default popup value for extension if tab specific value not available

---

patches/master_patch.patch

fix https://github.com/brave/browser-laptop/issues/8897

Don't check autoplay setting when play is trigger by user gesture

---

atom/app/atom_content_client.cc
atom/app/atom_content_client.h
brave/browser/component_updater/widevine_cdm_component_installer.cc

fix https://github.com/brave/browser-laptop/issues/10449
~required https://github.com/brave/browser-laptop-bootstrap/pull/21~
To reviewers:
1. Ask me for the cert, keys and passphrase
2. Ask me for the `signature_generator.py` from widevine
3. Copy `signature_generator.py` into `//third_party/widevine/scripts/signature_generator.py` before building with `sign_widevine`
---

Verify CDM host files

---

atom/common/api/resources/web_view_api_bindings.js
patches/master_patch.patch

So thtat it doesn't use the old value on re-attach
Auditors: @bridiver

Reset guest proxy routing ID

---

patches/master_patch.patch

This allows us to enable widevine safely in the bootstrap build in linux

Step 1 in enabling widevine

---

brave/browser/brave_content_browser_client.cc

This should fix https://github.com/brave/browser-laptop/issues/10849. Tested on Linux and Windows.

Expose missing spell checking interface

---

patches/master_patch.patch

Fix https://github.com/brave/browser-laptop/issues/8472

Fix 175% DPI selection bug

---

lib/browser/guest-view-manager.js
lib/renderer/web-view/guest-view-internal.js

prereq for https://github.com/brave/browser-laptop/issues/8574

don’t unregister guest events on crash

---

atom/browser/browser_linux.cc

Make desktop name configurable from browser-laptop

---

atom/browser/api/atom_api_menu.h
atom/browser/api/atom_api_menu_mac.h
atom/browser/api/atom_api_menu_mac.mm
atom/browser/api/atom_api_menu_views.cc
atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
lib/browser/api/menu.js
lib/browser/api/web-contents.js
patches/master_patch.patch

always call SetShowingContextMenu/NotifyContextMenuClosed
fix https://github.com/brave/browser-laptop/issues/10563
also fixes flash context menu items not working

fix webkit bug with release of context menu node

---

brave/utility/importer/chrome_importer.cc

We will always apply secure scheme when cookie is secure
@Auditors: @bsclifton, @bbondy

Remove wrong strict secure condition. 

---

atom/common/api/resources/windows_bindings.js
lib/browser/api/extensions.js

Implements the `chrome.windows.remove` method.
Fixes https://github.com/brave/browser-laptop/issues/8678

Implements chrome.windows.remove method

---

brave/utility/importer/chrome_importer.cc

when import encrypted cookie value from Chrome on Linux
fix https://github.com/brave/browser-laptop/issues/11280
note: it will create a new utility process each time importing cookies

Fix OSCrypt::DecryptString crash by preventing null config getting

---

atom/browser/browser_linux.cc

fix https://github.com/brave/browser-laptop/issues/11330
Auditors: @brividr, @bsclifton, @bbondy

Check args before using it

---

brave/utility/importer/chrome_importer.cc

fix https://github.com/brave/browser-laptop/issues/11280 again

Don't call OSCrypt::IsEncryptionAvailable which will directly get password before SetConfig()

---

BUILD.gn
atom/utility/atom_content_utility_client.cc
brave/utility/importer/brave_profile_import_service.cc
brave/utility/importer/brave_profile_import_service.h
patches/master_patch.patch

This will fix import cookies/passwords from Chrome on chromium 62 or you will see `Importer could not be created.` from `chrome/utility/importer/profile_import_impl.cc`

Overrides service_manager::Service::OnStart() for BraveProfileImportService

---

atom/browser/extensions/atom_extension_system.cc

Calling `TriggerOnWillBeInstalled` to make `LazyEventDispatchUtil::ReadPendingOnInstallInfoFromPref` return true
fix https://github.com/brave/browser-laptop/issues/8685
Auditors: @bridiver, @kevinlawler, @bbondy

Implement chrome.runtime.onInstalled

---

atom/common/api/resources/browser_action_bindings.js
atom/common/api/resources/context_menus_bindings.js
atom/common/api/resources/windows_bindings.js
lib/browser/api/extensions.js

Initial work to add support for `chrome.windows.create`.
Resolves https://github.com/brave/browser-laptop/issues/6789

Implements chrome.windows.create

---

atom/app/atom_main.cc
patches/master_patch.patch

Ctrl + Shift + Tab" will get a wrong command id (Ctrl + Tab) after calling performKeyEquivalent when webview.focus()
ex. navigating from new tab or fullscreen will reproduce
fix brave/browser-laptop#11331

Send key event to menu when webview focused

---

atom/browser/api/atom_api_web_contents.cc

don’t handle renderer messages when webcontents is being destroyed

---

atom/browser/net/atom_network_delegate.cc

block the following request after first blocked request
fix https://github.com/brave/browser-laptop/issues/12233

Using net::ERR_ABORTED instead of net::ERR_BLOCKED_BY_CLIENT which will

---

atom/browser/api/atom_api_web_contents.cc
atom/common/native_mate_converters/net_converter.cc
lib/renderer/web-view/guest-view-internal.js

I added code in `atom_api_web_contents.cc` to broadcast the organization name and country code for EV certificates to the frontend. For example, for github.com this string would be "GitHub, Inc. [US]".
Warning: we were running into some issues with the build, so we haven't attempted to compile this code yet! Please double check that everything is ready to go before merging.

Broadcast EV certificate information to the frontend

---

atom/browser/login_handler.cc

fix https://github.com/brave/browser-laptop/issues/12327

Fix basic auth crash by content::WebContents::FromFrameTreeNodeId

---

BUILD.gn
atom/browser/javascript_environment.cc
brave/common/extensions/crypto_bindings.cc
brave/common/extensions/crypto_bindings.h

master key is same as built-in password manager/cookies
Using base64 to encode non ASCII characters
fix https://github.com/brave/browser-laptop/issues/10705
Auditors: @bridiver, @diracdeltas, @bbondy

Implement muon.crypto.encryptString/decryptString API

---

patches/master_patch.patch

1. Audio element should also repect auotplay setting
fix brave/browser-laptop#11988
fix brave/browser-laptop#11527
2. Don't check user initiated video
fix brave/browser-laptop#12149
3. Default allow muted media
fix brave/browser-laptop#12152
4. Default allow for local files
fix brave/browser-laptop#8929

Autoplay issues fix

---

atom/browser/BUILD.gn
atom/browser/atom_browser_main_parts.cc

fix https://github.com/brave/browser-laptop/issues/12489
Auditors: @bridiver, @diracdeltas, @bbondy

Disable password autofill upon page load

---

atom/renderer/content_settings_manager.cc
atom/renderer/content_settings_manager.h
brave/renderer/extensions/content_settings_bindings.cc
chromium_src/chrome/renderer/content_settings_observer.cc

fixes crash for content settings when site isolation is enabled

only check origin for remote webframes - https://crbug.com/628759

---

brave/browser/password_manager/brave_password_manager_client.cc
brave/browser/password_manager/brave_password_manager_client.h

fix https://github.com/brave/browser-laptop/issues/12563
Auditors: @bridiver, @diracdeltas
Test plan:
a.
1. Make sure built-in password manager is enabled
2. Male sure passphrase is set on trezor wallet
3. Plugin trezor and open wallet
4. Type passphrase and submit
5. Brave shouldn't prompt any messages to save password
b.
1. Make sure built-in password manager is enabled
2. Sign up account for https://trac.torproject.org
3. Brave should ask users to save password, click deny
4. Logout and Login
5. Brave should ask users to save password, click allow
6. Change password
7. Brave should ask users to update password, click allow
8. Logout and use the save credentials to login
9. It should be able to login sucessfully

Do not prompt users to save password on passphrase confirmation page

---

atom/browser/net/atom_network_delegate.cc

Needed for session.webRequest.onHeadersReceived in order to implement https://github.com/brave/browser-laptop/issues/12671

Expose remote IP and port in webRequest details

---

patches/master_patch.patch

Needed for https://github.com/brave/browser-laptop/issues/12510

Allow rev_checking_enabled to be true in muon

---

atom/browser/api/atom_api_session.cc

needed for https://github.com/brave/browser-laptop/pull/12987 (it uses ses.setProxy to check whether a Tor process is running before Tor Tabs can be enabled)

run setProxy callback

---

app/BUILD.gn

fresh windows build fails with missing generated file for manifest overlay

fix windows build error

---

atom/browser/native_window_mac.mm

Fix #445 
This is a simple copy/paste of a fix in Electron:
https://github.com/electron/electron/pull/11164/files

Hide title bar bg on Mac for non-normal styles.

---

app/mac/resources/app-Info.plist
app/mac/resources/helper-Info.plist

https://hackerone.com/bugs?report_id=313440
Test:
- Open - https://nodejs.org/dist/v8.9.4/node-v8.9.4.pkg
- Run -
> $ xattr ~/Downloads/node-v8.9.4.pkg
> com.apple.metadata:kMDItemWhereFroms
> com.apple.quarantine
> 
Quarantine flag should be enabled for the file
fix https://github.com/brave/browser-laptop/issues/13088

Downloaded files on macOS should be quarantined by default

---

atom/browser/atom_download_manager_delegate.cc

fix https://github.com/brave/browser-laptop/issues/13230
fix https://github.com/brave/browser-laptop/issues/13228

Obtain extension from path when no mime type available

---

atom/browser/api/atom_api_dialog.cc

when DIR_DEFAULT_DOWNLOADS got home directory or desktop
fix https://github.com/brave/browser-laptop/issues/13229
fix https://github.com/brave/browser-laptop/issues/13255

Using `DIR_DEFAULT_DOWNLOADS_SAFE` 

---

atom/browser/net/atom_network_delegate.cc

AtomNetworkdelegate::OnURLRequestDestroyed() shouldn't be called in AtomNetworkdelegate::OnCompleted(). It causes calling AtomExtensionsNetworkDelegate::OnURLRequestDestroyed().
Before brave/muon@fb67093, OnCompleted() just cleanup internal data structure not by calling OnURLRequestDestroyed(). OnURLRequestDestroyed() only should be called by NetworkDelegate::NotifyURLRequestDestroyed().

Make AtomNetworkdelegate::OnCompleted() cleanup internal data directly

---

.gitattributes
DEPS
patches/master_patch.patch
script/apply-patches.py

This patch change should fail to apply once we get the upstream commits

Upstream commits for parent/child surface id

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/common_web_contents_delegate.cc
atom/browser/common_web_contents_delegate.h
vendor/brightray/browser/inspectable_web_contents_delegate.h
vendor/brightray/browser/inspectable_web_contents_impl.cc
vendor/brightray/browser/inspectable_web_contents_impl.h

fix brave/browser-laptop#13521

Add filesystem `type` for dev tools

---

atom/browser/api/atom_api_web_contents.cc
brave/browser/brave_browser_context.cc
lib/browser/api/extensions.js

THIS PR IS NOT ACTUALLY TO BE MERGED!  The same semantic changes are to be replayed on top of @darkdh's work to use a utility process rather than LaunchProcess.
Adds option `tor_data_dir` and adjusts parsing of option `tor_proxy`, and passes arguments down to the tor program so that tor will run in the right data directory and listen on the right socks port and not pick up any torrc in /etc or whatever.
Addresses https://github.com/brave/muon/issues/530.

Pass socks port, data directory to tor subprocess

---

atom/browser/atom_browser_context.cc
atom/browser/atom_download_manager_delegate.cc
atom/browser/atom_download_manager_delegate.h

Fix: https://github.com/brave/muon/issues/558

Fix NULL deref when deleting download prefs

---

app/mac/resources/app-Info.plist
app/mac/resources/helper-Info.plist

Part 1 of 2 for fixing https://github.com/brave/browser-laptop/issues/13817
Auditors: @jumde
This reverts commit 9a41781e34705fc1c82eaa93193961e2b6a57920, reversing
changes made to 974a1e90174689cd80931553e03c31433551f0aa.

Revert "Merge pull request #484 from brave/quarantine_downloads"

---

script/update-external-binaries.py

This should bring in Squirrel.Mac https://github.com/Squirrel/Squirrel.Mac/commit/cb838776ce22bcbf41def7b9a1352f24120bab29
And potentially fix https://github.com/brave/browser-laptop/issues/2184
Previously I submitted #573 which updated to binaries v1.2.2/Squirrel.Mac v0.3.2, but that was closed in favor of using the latest binaries v1.3.0/Squirrel.Mac https://github.com/Squirrel/Squirrel.Mac/commit/cb838776ce22bcbf41def7b9a1352f24120bab29, according to the comment by @diracdeltas https://github.com/brave/muon/pull/573#issuecomment-381700071

Update external binaries to 1.3.0 for latest Squirrel.Mac

---

chromium_src/BUILD.gn
chromium_src/chrome/browser/themes/theme_service.cc
chromium_src/chrome/browser/themes/theme_service_factory.cc
patches/master_patch.patch

Fixes build failure on linux:
```
[11691/11692] LINK ./brave
FAILED: brave 
...
/src/src/out/Release/../../third_party/llvm-build/Release+Asserts/bin/ld.lld: error: undefined symbol: ThemeServiceFactory::GetForProfile(Profile*)
>>> referenced by renderer_preferences_util.cc:142 (../../chrome/browser/renderer_preferences_util.cc:142)
>>>               obj/electron/chromium_src/renderer/renderer_preferences_util.o:(renderer_preferences_util::UpdateFromSystemSettings(content::RendererPreferences*, Profile*, content::WebContents*))
```

Fix renderer deps on linux

---

atom/browser/api/atom_api_web_contents.cc
atom/browser/api/atom_api_web_contents.h
patches/master_patch.patch

Test:
- Checkout `safe_browsing_api` in `browser-laptop`
- Navigate to: testsafebrowsing.appspot.com
- Select any `Webpage Warnings` links and see if the safe browsing warning is displayed.

Same safe browsing page should be displayed for all lists

---

atom/browser/extensions/atom_extension_web_contents_observer.cc
atom/browser/extensions/atom_extension_web_contents_observer.h

https://chromium.googlesource.com/chromium/src/+/399b6c3d211c09e1e0a003e8edb547043535bf77
fix https://github.com/brave/browser-laptop/issues/14252

 Explicitly calling `ExtensionWebContentsObserver::Initialize`

---

patches/master_patch.patch

The other side of bridge (RenderWidgetHostViewCocoa) of legacy webview is not valid
https://chromium.googlesource.com/chromium/src/+/98581bb30ea1eaebee3c3e4fb4c49e4a2446deca
fix https://github.com/brave/browser-laptop/issues/14247
Auditor: @bridiver, @hferreiro, @ltilve

RenderWidgetHostNSViewBridge::SetTargetView for legacy webview

---

lib/browser/api/web-contents.js

Fixes https://github.com/brave/browser-laptop/issues/14197
Auditors: @petemill, @bridiver

Check if web contents is attached before allowing it to be considered as focused

---

vendor/brightray/browser/browser_context.cc

This is necessary because we use `persist:tor` since for hysterical
raisins there's only one normal `private' partition with in_memory_ =
true.  We use the virtual method IsOffTheRecord() to discriminate
instead.
Fixes https://github.com/brave/muon/issues/608.
Fixes https://github.com/brave/browser-laptop/issues/14392.
Auditors: @darkdh

Propagate off-the-recordness to URL request context.

---

atom/browser/api/atom_api_dialog.cc

miscommunication in
https://github.com/brave/muon/pull/508#pullrequestreview-100614944
fix https://github.com/brave/browser-laptop/issues/14407
Auditors: @bridiver, @jumde

Remove DIR_DEFAULT_DOWNLOADS_SAFE which is covered by DownloadPrefs

---

brave/browser/net/proxy_resolution/proxy_config_service_tor.cc
brave/browser/net/proxy_resolution/proxy_config_service_tor.h

Don't just expire any old entries for the site we're browsing -- that
may leave lots of other ones around in memory.

Use a priority queue to expire all >10min-old tor circuit records.

---

atom/browser/atom_download_manager_delegate.cc

even when safe browsing is disabled
fix https://github.com/brave/browser-laptop/issues/14398
Auditors: @bridiver, @bbondy, @jumde

Workaround danger_type return from DownloadTargetDeterminer is marked dangerous 

---

brave/browser/net/proxy_resolution/proxy_config_service_tor.cc
brave/browser/net/proxy_resolution/proxy_config_service_tor.h

The timer is scheduled to run ten minutes after the last circuit that
was created.  This way, the last ten minutes of circuits are not
guaranteed to stick around in memory indefinitely.
Caveat: This doesn't _zero_ the memory, so it may still appear in
`strings /proc/N/mem`.  But it does make the memory available to be
recycled, so it's not _guaranteed_ to still appear in `strings
/proc/N/mem`.
Also, timestamp the map entries.  If we explicitly create a new map
entry for a site by requesting a new identity, the old expiry queue
entry will not delete it, but a new expiry queue entry will delete
it.  This way, circuits created by requesting a new identity are not
shorter-lived than other circuits.
We leave the old entries in the priority queue because there's no
convenient way to delete them …

Use a timer to expire circuits promptly.

---

patches/master_patch.patch

which will eventuall lead us to
`ContentSettingsObserver::AllowScriptFromSource`
https://chromium.googlesource.com/chromium/src/+/ea9b5b7daa1d3390b600f2efcaaa5ce3444bc244
It was safe before this commit because persistent client hint feature
wasn't enabled by default
fix https://github.com/brave/browser-laptop/issues/14582

Check resource type is javascript before calling AllowScriptFromSourceWithoutNotifying

---

brave/browser/BUILD.gn
brave/browser/brave_content_browser_client.cc
brave/browser/renderer_host/brave_render_message_filter.cc
brave/browser/renderer_host/brave_render_message_filter.h

1. Visit https://raananw.github.io/WebWorkers-IndexedDB/
2. Ensure your `Cookie Control` shields are set to `Block 3rd Party Cookies`
3. Click the `Run @ WebWorker` button
4. Scrollbar should go across the screen
5. Toggle the `Cookie Control` shields setting to `Block all cookies`
6. Click the `Run @ WebWorker` button
7. Scrollbar should not move
1. Visit https://mdn.github.io/dom-examples/web-storage/
2. Ensure your `Cookie Control` shields are set to `Block 3rd Party Cookies`
3. Pick a color from the `Choose background color` drop down
4. Verify the background color of page changes
5. Toggle the `Cookie Control` shields setting to `Block all cookies`
6. Notice the background color reset back to red
7. Try to change the color using the `Choose background color`
8. Notice the background …

Add support for missing events (fix indexedDB, etc)

---

atom/browser/atom_browser_context.cc
chromium_src/chrome/browser/ui/webui/chrome_web_ui_controller_factory.cc

and don't covert brave:// to file://
credit the patch to @bridiver
fix brave/browser-laptop#14642
Auditor: @bridiver, @diracdeltas

Handle file:// with net::FileProtocolHandler

---

patches/master_patch.patch

fix https://github.com/brave/browser-laptop/issues/14636
SuicideOnChannelErrorFilter calls exit in OnChannelError() this will
cause other endpoints listener can't finish their cleanup when pipe error
happens(browser process crashed or be killed) and
SuicideOnChannelErrorFilter::OnChannelError happens to be called before others.
This should be fine for most of the cases but not tor_launcher service.
`TorLauncher` requires StrongBinding::OnConnectionError to delete itself
so that `~TorLauncher` will get called and terminate tor process.
This should only happens on MacOS, SuicideOnChannelErrorFilter is
guarded by OS_POSIX and Linux has `prctl(PR_SET_PDEATHSIG, SIGKILL)`
so tor process will receive SIGKILL when tor_launcher utility process terminates
prematurely
Auditors: @riastradh-brave, …

Prevent `SuicideOnChannelErrorFilter` to be added to tor_launcher utility process

---

atom/browser/atom_download_manager_delegate.cc

Fix https://github.com/brave/browser-laptop/issues/14625
1. Disable "Always Ask Where to Save Files"
- Download a file. The file prompt should not displayed and the file should be successfully downloaded.
- Change the path and download the same file again. The file prompt should not displayed and the file should be successfully downloaded at the new location
2. Enable "Always Ask Where to Save Files"
- Download a file. The file prompt should be displayed and the file should be successfully downloaded.
- Change the path and download the same file again. The file prompt should be displayed and the file should be successfully downloaded at the new location

Check if file save prompt is required before saving files

---

atom/browser/extensions/atom_browser_client_extensions_part.cc

From ChromeContentBrowserClientExtensionsPart::ShouldAllowOpenURL
Possibly fix https://github.com/brave/browser-laptop/issues/14772

Update AtomBrowserClientExtensionsPart::ShouldAllowOpenURL from upstream

---

brave/browser/brave_content_browser_client.cc

because the result of
`extension_l10n_util::CurrentLocaleOrDefault` will be normalized by
`l10n_util::NormalizeLocale` which means turning en-US to en_US
`chrome.i18n.getUILanguage` uses `RenderThread::GetLocale()` which reads
from switch `--lang` appended when renderer process created and the
value is reading from `ContentBrowserClient::GetApplicationLocale`
fix https://github.com/brave/browser-laptop/issues/11624

Use `BrowserProcessImpl::GetApplicationLocale` for `BraveContentBrowserClient::GetApplicationLocale`

---

atom/browser/atom_browser_context.cc

Part of https://github.com/brave/browser-laptop/issues/14712
depends on https://github.com/brave/browser-laptop-bootstrap/pull/46

Check buildflag for whether FTP is disabled

---

atom/browser/api/atom_api_app.cc
atom/browser/api/atom_api_app.h

To be used to properly solve https://github.com/brave/browser-laptop/issues/14647
- Was unable to use the existing `electron.app.getLocale` method because it would return the language (not the country)
- I also looked at existing ICU methods and methods in the l10n/i18n helpers in Chromium's `base` namespace, but those all returned empty string for locale (as if it wasn't initialized properly)
- I briefly looked at node/native node modules and it looked too messy and unfruitful to go that route
This PR can be merged into C68 AND C69. ex: would be good to have a 8.0.10 and a 8.1.x build 😄

Add API method: electron.app.getCountryName

---

atom/browser/api/atom_api_user_prefs.cc
brave/browser/brave_browser_context.cc
brave/browser/brave_browser_context.h
chromium_src/chrome/browser/profiles/profile.h

With https://chromium.googlesource.com/chromium/src/+/f623bafe9c5b8cbd1d63c4d7c9b69de172552df5, the values being registered in a session were changed from an exclusion (ex: which values to NOT put in `OverlayUserPrefStore`) to an inclusion (ex: which values to PERSIST, even in an incognito profile)
Fixes https://github.com/brave/browser-laptop/issues/15191

Update incognito session initialization

---

README.md
docs/tutorial/moving-from-electron.md

I'm currently in the process of moving an app from Electron to Muon which has led me to a number of surprises. Along the way I've documented what I've found in hopes of making it easier for other developers.
[Here's a preview of the guide so far.](https://github.com/samuelmaddock/muon/blob/electron-guide/docs/tutorial/moving-from-electron.md) Let me know what you think!
It would also be useful to merge #417 to complement this guide.

Add guide for moving to Muon from Electron
